### ISSUE TITLE
Permissions Drop , this is the error i get

### ISSUE THREAD

**Issue by mcraftpete** [geNAZt/CloudChat#102]
09:01:31 [INFO] LOADED DATA: Robin161 a9d099aa90a74b1f89aaaa2e557ba6a6 true null null
09:01:31 [INFO] Â§dWelcome Â§fRobin161 Â§dto a1craft.com!
09:01:31 [INFO] Loaded player Â§9Robin161
09:01:31 [INFO] [CloudChat] Loading PlayerDatabase for Robin161
09:01:31 [INFO] [Robin161] <-> ServerConnector [Hub] has connected
09:01:31 [SEVERE] [Robin161] -> UpstreamBridge - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:259)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:141)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:563)
    at net.md_5.bungee.protocol.packet.ClientSettings.read(ClientSettings.java:37)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:32)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:228)
    ... 20 more
09:01:31 [INFO] [Robin161] disconnected with: Â§fDecoderException : java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11) @ io.netty.handler.codec.ByteToMessageDecoder:259
09:01:31 [INFO] [CloudChat] Saving PlayerDatabase for Robin161
09:01:31 [INFO] [Robin161] -> UpstreamBridge has disconnected
09:01:32 [INFO] Robin161Â§e has joined the server!
09:01:32 [WARNING] No client connected for pending server!
09:01:32 [SEVERE] [CloudChat] PluginMessageTask was interrupted
java.lang.NullPointerException
    at com.iKeirNez.PluginMessageApiPlus.implementations.BungeeCordPacketManager.sendPluginMessage(BungeeCordPacketManager.java:24)
    at com.iKeirNez.PluginMessageApiPlus.PacketManager.sendPacket(PacketManager.java:233)
    at net.cubespace.lib.PluginMessage.PluginMessageTask.run(PluginMessageTask.java:34)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
09:01:32 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5fe1fa0f, id=0, owner=net.cubespace.CloudChat.CloudChatPlugin@3f047fc3, task=net.cubespace.lib.PluginMessage.PluginMessageTask@6d10aba0, delay=0, period=0, running=true) encountered an exception
java.lang.RuntimeException
    at net.cubespace.lib.PluginMessage.PluginMessageTask.run(PluginMessageTask.java:38)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
09:01:32 [INFO] [Robin161] <-> ServerConnector [Hub] has disconnected
09:01:32 [INFO] [/166.137.99.28:58392] <-> InitialHandler has connected
09:01:33 [INFO] [/67.160.200.8:57954] <-> InitialHandler has connected

**Comment by mcraftpete** [comment]
same issue each time it crashes , heres another sample..
06:12:31 [INFO] Loaded player Â§9alexisw3440
06:12:31 [INFO] [CloudChat] Loading PlayerDatabase for alexisw3440
06:12:32 [SEVERE] [alexisw3440] -> UpstreamBridge - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:259)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:141)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1161)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:563)
    at net.md_5.bungee.protocol.packet.ClientSettings.read(ClientSettings.java:37)
    at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:32)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:228)
    ... 20 more
06:12:32 [INFO] [alexisw3440] disconnected with: Â§fDecoderException : java.lang.IndexOutOfBoundsException: readerIndex(11) + length(1) exceeds writerIndex(11): UnpooledHeapByteBuf(ridx: 11, widx: 11, cap: 11) @ io.netty.handler.codec.ByteToMessageDecoder:259
06:12:32 [INFO] [alexisw3440] <-> ServerConnector [Hub] has connected
06:12:32 [INFO] [alexisw3440] -> UpstreamBridge has disconnected
06:12:32 [INFO] [CloudChat] Saving PlayerDatabase for alexisw3440
06:12:32 [INFO] alexisw3440Â§e has joined the server!
06:12:32 [WARNING] No client connected for pending server!
06:12:32 [SEVERE] [CloudChat] PluginMessageTask was interrupted
java.lang.NullPointerException
    at com.iKeirNez.PluginMessageApiPlus.implementations.BungeeCordPacketManager.sendPluginMessage(BungeeCordPacketManager.java:24)
    at com.iKeirNez.PluginMessageApiPlus.PacketManager.sendPacket(PacketManager.java:233)
    at net.cubespace.lib.PluginMessage.PluginMessageTask.run(PluginMessageTask.java:34)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
06:12:32 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@70a7545d, id=0, owner=net.cubespace.CloudChat.CloudChatPlugin@37d0df29, task=net.cubespace.lib.PluginMessage.PluginMessageTask@b70d5ba, delay=0, period=0, running=true) encountered an exception
java.lang.RuntimeException
    at net.cubespace.lib.PluginMessage.PluginMessageTask.run(PluginMessageTask.java:38)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
06:12:32 [INFO] [alexisw3440] <-> ServerConnector [Hub] has disconnected
06:12:32 [INFO] [/188.115.16.228:51287] <-> InitialHandler has connected
06:12:33 [INFO] [/66.87.115.128:12751] <-> InitialHandler has connected
06:12:35 [INFO] [CloudChat] Â§8[Â§7GÂ§8]Â§f[Â§aAvatarÂ§f]Â§fazertiop13000Â§r: et personne ne peut nous pier
06:12:35 [INFO] [/46.114.36.173:49671] <-> InitialHandler has connected
06:12:35 [WARNING] [/209.80.128.106:57339] <-> InitialHandler - read timed out
06:12:36 [INFO] [CloudChat] Saving PlayerDatabase for thatmcgamer
06:12:36 [INFO] [thatmcgamer] -> UpstreamBridge has disconnected
06:12:36 [INFO] [CloudChat] Player thatmcgamer left Channel global

**Comment by geNAZt** [comment]
Its a bungeecord error. I dont read Netty bytebufs. Due to this packet error the Player disconnects and the Permission getter fails.

**Comment by mcraftpete** [comment]
but when it breaks things like /msg cross server still works , just the perms to join channel etc break  ,and why would it break , what can I do to fix it ?

**Comment by mcraftpete** [comment]
is there anyway I can use this with essentials chat so essentials will go across server ?
