### ISSUE TITLE
Exception in AffixMessage.java:29

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#12]
I see these guys regularly in my logs:

```
[11:24:40 WARN]: [CloudChatBukkit] Task #29 for CloudChatBukkit v0.5.1 generated an exception
java.lang.NullPointerException
    at net.cubespace.CloudChatBukkit.Message.AffixMessage.send(AffixMessage.java:29) ~[?:?]
    at net.cubespace.CloudChatBukkit.Listener.PlayerJoin$1.run(PlayerJoin.java:33) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:67) ~[spigot.jar:git-Spigot-1216]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot.jar:git-Spigot-1216]

    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:583) [spigot.jar:git-Spigot-1216]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:259) [spigot.jar:git-Spigot-1216]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540) [spigot.jar:git-Spigot-1216]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446) [spigot.jar:git-Spigot-1216]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1216]
```

**Comment by geNAZt** [comment]
Its fixed in the current Version 0.5.2
