### ISSUE TITLE
Spam config error (dev build)

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#15]
Running a clean setup, start bungee, stop bungee and start bungee again, this error occurs:
(I am running a build from latest commit, so I know its "unsupported" :-) )

```
15:15:19 [SEVERE] Cannot load plugins\CloudChat\spam.yml
net.craftminecraft.bungee.bungeeyaml.bukkitapi.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:net.cubespace.Clou
dChat.Config.Sub.SpamEntry
 in 'string', line 2, column 3:
- !!net.cubespace.CloudChat.Config ...
  ^

at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.YamlConfiguration.loadFromString(YamlConfiguration.java:113)
at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.FileConfiguration.load(FileConfiguration.java:151)
at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.FileConfiguration.load(FileConfiguration.java:118)
at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:233)
at net.cubespace.lib.Configuration.Config.reload(Config.java:38)
at net.cubespace.lib.Configuration.Config.init(Config.java:109)
at net.cubespace.lib.Configuration.ConfigManager.initConfig(ConfigManager.java:38)
at net.cubespace.CloudChat.CloudChatPlugin.onEnable(CloudChatPlugin.java:38)

at net.md_5.bungee.api.plugin.PluginManager.loadAndEnablePlugins(PluginManager.java:200)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:200)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:67)
```

And config looks like this:

```
SpamRules:
- !!net.cubespace.CloudChat.Config.Sub.SpamEntry
  ActionIfReached: MUTE
  AmountOfMessages: 1000
  CommandToDispatch: ban %player Dont spam so much
  ExcludePermission: cloudchat.spam.rule1
  HowLongToMuteInSeconds: 30
  InHowMuchSeconds: 10
  KickMessage: You have been kicked for Spamming
  MuteMessage: You have been muted for %amount seconds due to spamming
```

**Comment by geNAZt** [comment]
Fixed in https://github.com/geNAZt/CloudChat/commit/e2574d362834a1b841e4531c76a9042044adc892
