### ISSUE TITLE
PircBot auto-rejoin after disconnect

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#19]
Don't know why it disconnects, but it disconnects With: (~PircBot@cm-84.211.113.xxx.getinternet.no) Quit (Read error: Connection reset by peer)
(No Messages in any logs)

if I reconnect using irc::reconnect, it rejoins the IRC-channel but Messages are starting to be duplicated like issue#9: https://github.com/geNAZt/CloudChat/issues/9

**Comment by geNAZt** [comment]
Can you install the latest Version from the Ci (http://bamboo.cube-space.net/) and make /cc:report on. Write something (so that it duplicates). Then /cc:report off and link in the Report generated ? (But be sure to black IPs and stuff out, the Report does not do that :D)

**Comment by Citaborg** [comment]
Ill keep it in mind if the duplication happens again :-)

**Comment by geNAZt** [comment]
And thanks for the support in finding Bugs :) You are awesome

**Comment by Citaborg** [comment]
Getting this when trying to load the CloudChatBukkit (or xxx-0.8.0) artifact from latest build on bamboo: 

```
[11:23:39 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/iKeirNez/PluginMessageApi
Plus/PacketListener
[11:23:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
[11:23:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:309)
[11:23:39 WARN]:        at net.skycraftmc.PluginManager.PluginControl.loadPlugin(PluginControl.java:72)
[11:23:39 WARN]:        at net.skycraftmc.PluginManager.PluginManagerPlugin.onCommand   (PluginManagerPlugin.java:206)
[11:23:39 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:23:39 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:196)
[11:23:39 WARN]:        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:546)
[11:23:39 WARN]:        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchServerCommand(CraftServer.java:533)
[11:23:39 WARN]:        at net.minecraft.server.v1_7_R1.DedicatedServer.aw(DedicatedServer.java:309)
[11:23:39 WARN]:        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:274)
[11:23:39 WARN]:        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540)
[11:23:39 WARN]:        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446)
[11:23:39 WARN]:        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)
[11:23:39 WARN]: Caused by: java.lang.NoClassDefFoundError:   com/iKeirNez/PluginMessageApiPlus/PacketListener
[11:23:39 WARN]:        at java.lang.Class.forName0(Native Method)
[11:23:39 WARN]:        at java.lang.Class.forName(Class.java:270)
[11:23:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
[11:23:39 WARN]:        ... 12 more
```

**Comment by geNAZt** [comment]
You installed this ? http://bamboo.cube-space.net/artifact/MC-CCB/JOB1/build-13/CloudChatBukkit/CloudChatBukkit.jar or http://bamboo.cube-space.net/artifact/MC-CCB/JOB1/build-13/CloudChatBukkit/CloudChatBukkit-0.8.0.jar ? The http://bamboo.cube-space.net/artifact/MC-CCB/JOB1/build-13/CloudChatBukkit/CloudChatBukkit.jar is the correct one (it is bundled with libs)

//Edit fixed the Bamboo building Script (now only one [the lib bundled] artifact comes out)

**Comment by Citaborg** [comment]
I started with CloudChatBukkit.jar and then the xxx-0.8.0.jar, getting the same Message on both...
*\* I will dl and retry once more to make sure I didn't skrew up saving the dl's.

**Comment by Citaborg** [comment]
I had dropped both files in my plugins folder :-/
My bad

**Comment by geNAZt** [comment]
Ok :) And i looked through my Code and thought like wut what ? No cant be :D
