### ISSUE TITLE
Exception: Unknown column 'channel' in 'field list'

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#25]
Plugin: CloudChat; Version: 2.8.1
BungeeCord: git-BungeeCord-Bootstrap-1.7-SNAPSHOT-"80caa2b"-783; Java: 1.7.0_40

```
18:20:03 [INFO] 2014-01-04 18:20:03,807 [DEBUG] JdbcPooledConnectionSource reusing connection #1759821582
18:20:03 [INFO] 2014-01-04 18:20:03,832 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `chatmessage` (`nick` ,`channel` ,`message` ,`date` ,`source` ,`ircChannel` ) VALUES (?,?,?,?,?,?)' and 6 args, threw exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'channel' in 'field list'
18:20:03 [INFO] 2014-01-04 18:20:03,833 [DEBUG] JdbcPooledConnectionSource cache released connection #1759821582
18:20:03 [SEVERE] [CloudChat] Error in AsyncDatabaseLogger
java.sql.SQLException: Unable to run insert stmt on object net.cubespace.CloudChat.Module.Logging.Entity.ChatMessage@4c1802de: INSERT INTO `chatmessage` (`nick` ,`channel` ,`message` ,`date` ,`source` ,`ircChannel` ) VALUES (?,?,?,?,?,?)
    at net.cubespace.vendor.com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
    at net.cubespace.vendor.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
    at net.cubespace.vendor.com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:438)
    at net.cubespace.vendor.com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
    at net.cubespace.CloudChat.Module.Logging.AsyncDatabaseLogger$1.run(AsyncDatabaseLogger.java:40)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'channel' in 'field list'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
    at com.mysql.jdbc.Util.getInstance(Util.java:386)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2366)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2350)
    at net.cubespace.vendor.com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:175)
    at net.cubespace.vendor.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
    ... 7 more  18:20:03 [INFO] 2014-01-04 18:20:03,807 [DEBUG] JdbcPooledConnectionSource reusing connection #1759821582
18:20:03 [INFO] 2014-01-04 18:20:03,832 [DEBUG] BaseMappedStatement insert data with statement 'INSERT INTO `chatmessage` (`nick` ,`channel` ,`message` ,`date` ,`source` ,`ircChannel` ) VALUES (?,?,?,?,?,?)' and 6 args, threw exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'channel' in 'field list'
18:20:03 [INFO] 2014-01-04 18:20:03,833 [DEBUG] JdbcPooledConnectionSource cache released connection #1759821582
18:20:03 [SEVERE] [CloudChat] Error in AsyncDatabaseLogger
java.sql.SQLException: Unable to run insert stmt on object net.cubespace.CloudChat.Module.Logging.Entity.ChatMessage@4c1802de: INSERT INTO `chatmessage` (`nick` ,`channel` ,`message` ,`date` ,`source` ,`ircChannel` ) VALUES (?,?,?,?,?,?)
    at net.cubespace.vendor.com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
    at net.cubespace.vendor.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
    at net.cubespace.vendor.com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:438)
    at net.cubespace.vendor.com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
    at net.cubespace.CloudChat.Module.Logging.AsyncDatabaseLogger$1.run(AsyncDatabaseLogger.java:40)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'channel' in 'field list'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
    at com.mysql.jdbc.Util.getInstance(Util.java:386)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2617)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2778)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2441)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2366)
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2350)
    at net.cubespace.vendor.com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:175)
    at net.cubespace.vendor.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
    ... 7 more
```

**Comment by Citaborg** [comment]
Database logging resumed when I manually added the Channel column
