### ISSUE TITLE
IRC bot disconnects (and does not reconnect)

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#27]
I left it on yesterday and today it was gone. No server or Proxy restarts. My internet Connection network and the normal IRC Client (mIRC) has not been disconnected. 

IRC this morning at about 06:30

```
* CitaBot (~PircBot@cm-84.211.113.xxx.getinternet.no) Quit (*.net *.split)
```

And in the log

```
06:30:49 [INFO] [CloudChat] Trying to reconnect to IRC
06:31:10 [SEVERE] [CloudChat] Could not reconnect IRC Bot
java.net.ConnectException: Connection timed out: connect
    at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at java.net.Socket.<init>(Socket.java:425)
    at java.net.Socket.<init>(Socket.java:208)
    at net.cubespace.vendor.org.jibble.pircbot.PircBot.connect(PircBot.java:140)
    at net.cubespace.vendor.org.jibble.pircbot.PircBot.reconnect(PircBot.java:248)
    at net.cubespace.CloudChat.Module.IRC.Bot.Bot.onDisconnect(Bot.java:243)
    at net.cubespace.vendor.org.jibble.pircbot.InputThread.run(InputThread.java:141)
```

This Block of retry -> timeout keeps repeating until I get the next error, then it seems it "gave up"

```
06:35:11 [SEVERE] [CloudChat] Could not reconnect IRC Bot
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:154)
    at java.io.BufferedReader.readLine(BufferedReader.java:317)
    at java.io.BufferedReader.readLine(BufferedReader.java:382)
    at net.cubespace.vendor.org.jibble.pircbot.PircBot.connect(PircBot.java:174)
    at net.cubespace.vendor.org.jibble.pircbot.PircBot.reconnect(PircBot.java:248)
    at net.cubespace.CloudChat.Module.IRC.Bot.Bot.onDisconnect(Bot.java:243)
    at net.cubespace.vendor.org.jibble.pircbot.InputThread.run(InputThread.java:141)
```

Running irc:reconnect command (much later :-)) the bot connected normally.

**Comment by Citaborg** [comment]
Oops... not latest Version of CC installed - I know you fixed some bot stuff :-)

**Comment by geNAZt** [comment]
Well i will improve the Code today (implement a retry counter) so the bot will not spam the IRC Network too much :)

**Comment by geNAZt** [comment]
https://github.com/geNAZt/CloudChat/commit/59bdbc639570b2c193d9a1de9fb107c1be579eb1
